name: Dry Run Maven Central Deployment

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-publish:
    name: Build & maven publish
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout for ${{ github.event.inputs.version }}
        uses: actions/checkout@v4.1.7

        # DO NOT USE CONTAINER, else gpg sign step will fail
        # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'
          # Set this in pom.xml
          server-id: ossrh-ershakiransari
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Building & Publishing artifact ${{ github.event.inputs.version }} to Maven Central
        run: |
          mvn clean deploy \
          -P release-dry-run \
          -DaltDeploymentRepository=ossrh-ershakiransari::default::file:/tmp/alt-repo \
          --no-transfer-progress -e
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
