name: Maven Clean Package

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "*" ]

jobs:
  build:
    name: Maven Clean Package
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:17-mvn3

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.7

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
